language: node_js
node_js:
  - "10"
install:
  - npm install
branches:
  except:
    - master
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: build
      script: npm run build

deploy:
  local-dir: ./dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: develop